---
title: "FBI Database Compilation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r load-packages, message = FALSE}
library(tidyverse)
library(knitr)
library(rvest)
library(lubridate)
library(infer)
library(readxl)
library(tm)
set.seed(460)
```

## Load Crime Data

```{r crime-data, message = FALSE}
crime_11 <- read_csv("fbi/2011_crimes_bycity.csv")
crime_12 <- read_csv("fbi/2012_crimes_bycity.csv")
crime_13 <- read_csv("fbi/2013_crimes_bycity.csv")
crime_14 <- read_csv("fbi/2014_crimes_bycity.csv")
crime_15 <- read_csv("fbi/2015_crimes_bycity.csv")
crime_16 <- read_csv("fbi/2016_crimes_bycity.csv")
crime_17 <- read_csv("fbi/2018_crimes_bycity.csv")
crime_18 <- read_csv("fbi/2018_crimes_bycity.csv")
crime_19 <- read_csv("fbi/2019_crimes_bycity.csv")

```

## Crime Data Wrangling

```{r slice-footnotes}
crime_11 <- crime_11 %>% 
  slice(1:9314)
crime_12 <- crime_12 %>% 
  slice(1:9491)
crime_13 <- crime_13 %>% 
  slice(1:9292)
crime_14 <- crime_14 %>% 
  slice(1:9347)
crime_15 <- crime_15 %>% 
  slice(1:9395)
crime_16 <- crime_16 %>% 
  slice(1:9579)
crime_17 <- crime_17 %>% 
  slice(1:9579)
crime_18 <- crime_18 %>% 
  slice(1:9252)
crime_19 <- crime_19 %>% 
  slice(1:8105)

```


```{r fill-msa-names}
crime_11 <- crime_11 %>% 
  mutate(year = "2011") %>% 
  fill(State, .direction = "down")

crime_11$State <- crime_11$State %>% 
  str_replace("ALABAMA2", "ALABAMA")

crime_12 <- crime_12 %>% 
  mutate(year = "2012") %>% 
  fill(State, .direction = "down")

crime_13 <- crime_13 %>% 
  mutate(year = "2013") %>% 
  fill(State, .direction = "down")

crime_14 <- crime_14 %>% 
  mutate(year = "2014") %>% 
  fill(State, .direction = "down")

crime_15 <- crime_15 %>% 
  mutate(year = "2015") %>% 
  fill(State, .direction = "down")

crime_16 <- crime_16 %>% 
  mutate(year = "2016") %>% 
  fill(State, .direction = "down")

crime_17 <- crime_17 %>% 
  mutate(year = "2017") %>% 
  fill(State, .direction = "down")

crime_18 <- crime_18 %>% 
  mutate(year = "2018") %>% 
  fill(State, .direction = "down")

crime_19 <- crime_19 %>% 
  mutate(year = "2019") %>% 
  fill(State, .direction = "down")
```

```{r combine-data}
all_crimes <- full_join(crime_11, crime_12)
all_crimes <- full_join(all_crimes, crime_13)
all_crimes <- full_join(all_crimes, crime_14)
all_crimes <- full_join(all_crimes, crime_15)
all_crimes <- full_join(all_crimes, crime_16)
all_crimes <- full_join(all_crimes, crime_17)
all_crimes <- full_join(all_crimes, crime_18)
all_crimes <- full_join(all_crimes, crime_19) #can solve forcible rape/rape1 problem by just changing rape1 name to forcible rape
```

```{r wrangle-all-crimes}
names(all_crimes)[1] <- "state"
names(all_crimes)[2] <- "city"
names(all_crimes)[3] <- "population"
names(all_crimes)[4] <- "violent_crime"
names(all_crimes)[9] <- "property_crime"
all_crimes <- all_crimes %>%
  select(state, city, population, violent_crime, property_crime, year) %>% 
  mutate(violent_crime_rate = violent_crime / population * 100000) %>% 
  mutate(property_crime_rate = property_crime / population * 100000)

all_crimes$state <- removeNumbers(all_crimes$state)
all_crimes$city <- removeNumbers(all_crimes$city)
all_crimes$state <- str_remove(all_crimes$state, ", ")
all_crimes$city <- str_remove(all_crimes$city, ", ")
all_crimes$city <- str_remove(all_crimes$city, ",")
all_crimes$state <- str_to_title(all_crimes$state)
```


## Load Census Data

```{r load-census-data, message = FALSE}
social_acs_2011 <- read_csv("census/2011_social_acs.csv")
economic_acs_2011 <- read_csv("census/2011_economic_acs.csv")
housing_acs_2011 <- read_csv("census/2011_housing_acs.csv") 
demographic_acs_2011 <- read_csv("census/2011_demographic_acs.csv")
social_acs_2012 <- read_csv("census/2012_social_acs.csv")
economic_acs_2012 <- read_csv("census/2012_economic_acs.csv")
housing_acs_2012 <- read_csv("census/2012_housing_acs.csv") 
demographic_acs_2012 <- read_csv("census/2012_demographic_acs.csv")
social_acs_2013 <- read_csv("census/2013_social_acs.csv")
economic_acs_2013 <- read_csv("census/2013_economic_acs.csv")
housing_acs_2013 <- read_csv("census/2013_housing_acs.csv") 
demographic_acs_2013 <- read_csv("census/2013_demographic_acs.csv")
social_acs_2014 <- read_csv("census/2014_social_acs.csv")
economic_acs_2014 <- read_csv("census/2014_economic_acs.csv")
housing_acs_2014 <- read_csv("census/2014_housing_acs.csv") 
demographic_acs_2014 <- read_csv("census/2014_demographic_acs.csv")
social_acs_2015 <- read_csv("census/2015_social_acs.csv")
economic_acs_2015 <- read_csv("census/2015_economic_acs.csv")
housing_acs_2015 <- read_csv("census/2015_housing_acs.csv") 
demographic_acs_2015 <- read_csv("census/2015_demographic_acs.csv")
social_acs_2016 <- read_csv("census/2016_social_acs.csv")
economic_acs_2016 <- read_csv("census/2016_economic_acs.csv")
housing_acs_2016 <- read_csv("census/2016_housing_acs.csv") 
demographic_acs_2016 <- read_csv("census/2016_demographic_acs.csv")
social_acs_2017 <- read_csv("census/2017_social_acs.csv")
economic_acs_2017 <- read_csv("census/2017_economic_acs.csv")
housing_acs_2017 <- read_csv("census/2017_housing_acs.csv") 
demographic_acs_2017 <- read_csv("census/2017_demographic_acs.csv")
social_acs_2018 <- read_csv("census/2018_social_acs.csv")
economic_acs_2018 <- read_csv("census/2018_economic_acs.csv")
housing_acs_2018 <- read_csv("census/2018_housing_acs.csv") 
demographic_acs_2018 <- read_csv("census/2018_demographic_acs.csv")
social_acs_2019 <- read_csv("census/2019_social_acs.csv")
economic_acs_2019 <- read_csv("census/2019_economic_acs.csv")
housing_acs_2019 <- read_csv("census/2019_housing_acs.csv") 
demographic_acs_2019 <- read_csv("census/2019_demographic_acs.csv")
```
  


```{r}
social_acs_2011 <- social_acs_2011 %>% 
  select(NAME, DP02_0008PE, DP02_0066PE, DP02_0079PE) %>% 
  mutate(year = "2011")
economic_acs_2011 <- economic_acs_2011 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2011")
housing_acs_2011 <- housing_acs_2011 %>% 
  select(NAME, DP04_0045PE) %>% 
  mutate(year = "2011")
demographic_acs_2011 <- demographic_acs_2011 %>% 
  select(NAME, DP05_0018PE, DP05_0072PE) %>% 
  mutate(year = "2011")
social_acs_2012 <- social_acs_2012 %>% 
  select(NAME, DP02_0008PE, DP02_0066PE, DP02_0079PE) %>% 
  mutate(year = "2012") %>% 
  slice(-1)
economic_acs_2012 <- economic_acs_2012 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2012") %>% 
  slice(-1)
housing_acs_2012 <- housing_acs_2012 %>% 
  select(NAME, DP04_0045PE) %>% 
  mutate(year = "2012") %>% 
  slice(-1)
demographic_acs_2012 <- demographic_acs_2012 %>% 
  select(NAME, DP05_0018PE, DP05_0072PE) %>% 
  mutate(year = "2012") %>% 
  slice(-1)

social_acs_2013 <- social_acs_2013 %>% 
  select(NAME, DP02_0008PE, DP02_0066PE, DP02_0079PE) %>% 
  mutate(year = "2013") %>% 
  slice(-1)
economic_acs_2013 <- economic_acs_2013 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2013") %>% 
  slice(-1)
housing_acs_2013 <- housing_acs_2013 %>% 
  select(NAME, DP04_0045PE) %>% 
  mutate(year = "2013") %>% 
  slice(-1)
demographic_acs_2013 <- demographic_acs_2013 %>% 
  select(NAME, DP05_0018PE, DP05_0072PE) %>% 
  mutate(year = "2013") %>% 
  slice(-1)

social_acs_2014 <- social_acs_2014 %>% 
  select(NAME, DP02_0008PE, DP02_0066PE, DP02_0079PE) %>% 
  mutate(year = "2014") %>% 
  slice(-1)
economic_acs_2014 <- economic_acs_2014 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2014") %>% 
  slice(-1)
housing_acs_2014 <- housing_acs_2014 %>% 
  select(NAME, DP04_0045PE) %>% 
  mutate(year = "2014") %>% 
  slice(-1)
demographic_acs_2014 <- demographic_acs_2014 %>% 
  select(NAME, DP05_0018PE, DP05_0072PE) %>% 
  mutate(year = "2014") %>% 
  slice(-1)
  
social_acs_2015 <- social_acs_2015 %>% 
  select(NAME, DP02_0008PE, DP02_0066PE, DP02_0079PE) %>% 
  mutate(year = "2015") %>% 
  slice(-1)
economic_acs_2015 <- economic_acs_2015 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2015") %>% 
  slice(-1)
housing_acs_2015 <- housing_acs_2015 %>% 
  select(NAME, DP04_0046PE) %>% 
  mutate(year = "2015") %>% 
  slice(-1)
names(housing_acs_2015)[2] <- "DP04_0045PE"
demographic_acs_2015 <- demographic_acs_2015 %>% 
  select(NAME, DP05_0018PE, DP05_0072PE) %>% 
  mutate(year = "2015") %>% 
  slice(-1)

social_acs_2016 <- social_acs_2016 %>% 
  select(NAME, DP02_0008PE, DP02_0066PE, DP02_0079PE) %>% 
  mutate(year = "2016") %>% 
  slice(-1)
economic_acs_2016 <- economic_acs_2016 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2016") %>% 
  slice(-1)
housing_acs_2016 <- housing_acs_2016 %>% 
  select(NAME, DP04_0046PE) %>% 
  mutate(year = "2016") %>% 
  slice(-1)
names(housing_acs_2016)[2] <- "DP04_0045PE"
demographic_acs_2016 <- demographic_acs_2016 %>% 
  select(NAME, DP05_0018PE, DP05_0072PE) %>% 
  mutate(year = "2016") %>% 
  slice(-1)

social_acs_2017 <- social_acs_2017 %>% 
  select(NAME, DP02_0008PE, DP02_0066PE, DP02_0079PE) %>% 
  mutate(year = "2017") %>% 
  slice(-1)
economic_acs_2017 <- economic_acs_2017 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2017") %>% 
  slice(-1)
housing_acs_2017 <- housing_acs_2017 %>% 
  select(NAME, DP04_0046PE) %>% 
  mutate(year = "2017") %>% 
  slice(-1)
names(housing_acs_2017)[2] <- "DP04_0045PE"
demographic_acs_2017 <- demographic_acs_2017 %>% 
  select(NAME, DP05_0021PE, DP05_0077PE) %>% 
  mutate(year = "2017") %>% 
  slice(-1)
names(demographic_acs_2017)[2] = "DP05_0018PE"
names(demographic_acs_2017)[3] = "DP05_0072PE"

social_acs_2018 <- social_acs_2018 %>% 
  select(NAME, DP02_0008PE, DP02_0066PE, DP02_0079PE) %>% 
  mutate(year = "2018") %>% 
  slice(-1)
economic_acs_2018 <- economic_acs_2018 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2018") %>% 
  slice(-1)
housing_acs_2018 <- housing_acs_2018 %>% 
  select(NAME, DP04_0046PE) %>% 
  mutate(year = "2018") %>% 
  slice(-1)
names(housing_acs_2018)[2] <- "DP04_0045PE"
demographic_acs_2018 <- demographic_acs_2018 %>% 
  select(NAME, DP05_0021PE, DP05_0077PE) %>% 
  mutate(year = "2018") %>% 
  slice(-1)
names(demographic_acs_2018)[2] = "DP05_0018PE"
names(demographic_acs_2018)[3] = "DP05_0072PE"

social_acs_2019 <- social_acs_2019 %>% 
  select(NAME, DP02_0011PE, DP02_0067PE, DP02_0080PE) %>% 
  mutate(year = "2019") %>% 
  slice(-1)
names(social_acs_2019)[2] = "DP02_0008PE"
names(social_acs_2019)[3] = "DP02_0066PE"
names(social_acs_2019)[4] = "DP02_0079PE"
economic_acs_2019 <- economic_acs_2019 %>% 
  select(NAME, DP03_0049PE, DP03_0009PE, DP03_0062E, DP03_0074PE, DP03_0129PE) %>% 
  mutate(year = "2019") %>% 
  slice(-1)
housing_acs_2019 <- housing_acs_2019 %>% 
  select(NAME, DP04_0046PE) %>% 
  mutate(year = "2019") %>% 
  slice(-1)
names(housing_acs_2019)[2] <- "DP04_0045PE"
demographic_acs_2019 <- demographic_acs_2019 %>% 
  select(NAME, DP05_0021PE, DP05_0077PE) %>% 
  mutate(year = "2019") %>% 
  slice(-1)
names(demographic_acs_2019)[2] = "DP05_0018PE"
names(demographic_acs_2019)[3] = "DP05_0072PE"

```

```{r join-datasets, message = FALSE}
social_acs <- full_join(social_acs_2011, social_acs_2012)
social_acs <- full_join(social_acs, social_acs_2013)
social_acs <- full_join(social_acs, social_acs_2014)
social_acs <- full_join(social_acs, social_acs_2015)
social_acs <- full_join(social_acs, social_acs_2016)
social_acs <- full_join(social_acs, social_acs_2017)
social_acs <- full_join(social_acs, social_acs_2018)
social_acs <- full_join(social_acs, social_acs_2019)
economic_acs <- full_join(economic_acs_2011, economic_acs_2012)
economic_acs <- full_join(economic_acs, economic_acs_2013)
economic_acs <- full_join(economic_acs, economic_acs_2014)
economic_acs <- full_join(economic_acs, economic_acs_2015)
economic_acs <- full_join(economic_acs, economic_acs_2016)
economic_acs <- full_join(economic_acs, economic_acs_2017)
economic_acs <- full_join(economic_acs, economic_acs_2018)
economic_acs <- full_join(economic_acs, economic_acs_2019)
demographic_acs <- full_join(demographic_acs_2011, demographic_acs_2012)
demographic_acs <- full_join(demographic_acs, demographic_acs_2013)
demographic_acs <- full_join(demographic_acs, demographic_acs_2014)
demographic_acs <- full_join(demographic_acs, demographic_acs_2015)
demographic_acs <- full_join(demographic_acs, demographic_acs_2016)
demographic_acs <- full_join(demographic_acs, demographic_acs_2017)
demographic_acs <- full_join(demographic_acs, demographic_acs_2018)
demographic_acs <- full_join(demographic_acs, demographic_acs_2019)
housing_acs <- full_join(housing_acs_2011, housing_acs_2012)
housing_acs <- full_join(housing_acs, housing_acs_2013)
housing_acs <- full_join(housing_acs, housing_acs_2014)
housing_acs <- full_join(housing_acs, housing_acs_2015)
housing_acs <- full_join(housing_acs, housing_acs_2016)
housing_acs <- full_join(housing_acs, housing_acs_2017)
housing_acs <- full_join(housing_acs, housing_acs_2018)
housing_acs <- full_join(housing_acs, housing_acs_2019)

```

```{r change-names}
names(social_acs)[2] <- "female_household"
names(social_acs)[3] <- "hs"
names(social_acs)[4] <- "res_stability"
names(demographic_acs)[2] <- "over_18"
names(demographic_acs)[3] <- "white_percent"
names(economic_acs)[2] <- "self_employed"
names(economic_acs)[3] <- "unemployment"
names(economic_acs)[4] <- "median_income"
names(economic_acs)[5] <- "received_snap"
names(economic_acs)[6] <- "child_poverty"
names(housing_acs)[2] <- "owner_occupied"

social_acs <- social_acs %>% 
  slice(-1)

demographic_acs <- demographic_acs %>% 
  slice(-1)

economic_acs <- economic_acs %>% 
  slice(-1)

housing_acs <- housing_acs %>% 
  slice(-1)

```


```{r combine-acs}
full_acs <- full_join(social_acs, demographic_acs, by = c("NAME", "year"), include = TRUE)
full_acs <- full_join(full_acs, economic_acs, by = c("NAME", "year"), include - TRUE) 
full_acs <- full_join(full_acs, housing_acs, by = c("NAME", "year"), include = TRUE)
```


```{r full-acs}
full_acs <- full_acs %>% 
  mutate(female_household = as.numeric(female_household), 
         hs = as.numeric(hs), 
         res_stability = as.numeric(res_stability), 
         over_18 = as.numeric(over_18), 
         white_percent = as.numeric(white_percent), 
         self_employed = as.numeric(self_employed), 
         unemployment = as.numeric(unemployment), 
         median_income = as.numeric(median_income), 
         received_snap = as.numeric(received_snap), 
         child_poverty = as.numeric(child_poverty), 
         owner_occupied = as.numeric(owner_occupied)) 
full_acs$NAME <- str_replace(full_acs$NAME, " city, ", ", ")
full_acs$NAME <- str_replace(full_acs$NAME, " town, ", ", ")
full_acs$NAME <- str_replace(full_acs$NAME, " CDP, ", ", ")
full_acs$city <- str_split(full_acs$NAME, ", ", simplify = TRUE)[,1]
full_acs$state <- str_split(full_acs$NAME, ", ", simplify = TRUE)[,2]

```

```{r left-join}
full_database <- left_join(all_crimes, full_acs, by = c("city", "state", "year"))
```

```{r save-work}
write_csv(full_database, "data/crime_database.csv")
```


